### ISSUE TITLE
Error while running docker-compose up

### ISSUE THREAD

**Issue by absalan** [hitalos/laravel#13]
Hi There,

Thanks for useful package.
I have little issue here and not able to get it work:

λ docker-compose up
Starting laravel_db_1 ... done
Starting laravel_web_1 ... error

ERROR: for laravel_web_1  Cannot start service web: b'driver failed programming external connectivity on endpoint laravel_web_1 (8406510046a8e2ab3130ec73f8a6a9f7f9cebf703de...): Error starting userland proxy: Bind for 0.0.0.0:80 failed: port is already allocated'

ERROR: for web  Cannot start service web: b'driver failed programming external connectivity on endpoint laravel_web_1 (8406510046a8e2ab3130ec73f8a6a9f7f9cebf703debafa35...): Error starting userland proxy: Bind for 0.0.0.0:80 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.

Please let me know what's wrong.
Thanks

**Comment by hitalos** [comment]
Apparently you tried to using a already in use port.
Try to change *80:80* for *8080:80* in the `docker-compose.yml` by example.

**Comment by absalan** [comment]
Hi Hitalos,

I stopped the service and restarted my PC.
First time I run docker-compose up:

---------------------------------------------
λ docker-compose up
Starting laravel_db_1 ... done
Starting laravel_web_1 ... done
Attaching to laravel_db_1, laravel_web_1
db_1   | error: database is uninitialized and password option is not specified
db_1   |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
web_1  | Directory public does not exist.
laravel_db_1 exited with code 1
laravel_web_1 exited with code 1
----------------------------------------------
And running it again and this is what I got again:

λ docker-compose up
Creating laravel_db_1 ... done
Creating laravel_web_1 ... error

ERROR: for laravel_web_1  Cannot start service web: b'Cannot link to a non running container: /laravel_db_1 AS /laravel_web_1/db'

ERROR: for web  Cannot start service web: b'Cannot link to a non running container: /laravel_db_1 AS /laravel_web_1/db'
ERROR: Encountered errors while bringing up the project.
