### ISSUE TITLE
Python is missing when npm install on the laravel scaffold 

### ISSUE THREAD

**Issue by ice-blaze** [hitalos/laravel#14]
Because when we need to update the sass we need to do `npm install` and then `npm run dev` but I got an error that python is missing. My current workaround is to use a node image.

**Comment by hitalos** [comment]
For dependencies that need python, you can extend the image and install python and dependencies to construct the module. Ex.:
Add this line to you Dockerfile:
RUN apk -U add python make

**Comment by hitalos** [comment]
The `npm audit` command alerts about 10 vulnerabilities in the` node-sass` package. 
You should consider adopting a package made in pure JS as the [sass](https://www.npmjs.com/package/sass).  It's also too smaller.

**Comment by ice-blaze** [comment]
@hitalos Thank you for your help. 

It's a bit disappointing that

**Comment by hitalos** [comment]
I ran some tests and even with make, python, gcc and g++ packages, `libsass` won't build in alpine.
I trying to build a image tag based on debian to resolve these cases.
There were also problems with other dependencies.

**Comment by hitalos** [comment]
Ok, now you can try with `hitalos/laravel:debian`.

**Comment by ice-blaze** [comment]
Indeed it works well! 

`apk` is pain but I'm sure it's possible to build everything with alpine. I'll try and if it works I will do a PR.
