### ISSUE TITLE
Missing xdebug

### ISSUE THREAD

**Issue by unt0xication** [hitalos/laravel#19]
Hey! Is it possible to add support for php xdebug? It would be useful for coverage reports :)

**Comment by hitalos** [comment]
I am rebuilding the base image `hitalos/php` to add xdebug in this moment. After that, I will rebuild `hitalos/laravel` too.

**Comment by unt0xication** [comment]
poke me when it's ready!

**Comment by unt0xication** [comment]
Also, it would be nice to add support to run laravel dusk tests :)

**Comment by hitalos** [comment]
OK, it's done. Can you test `xdebug` functionality?

**Comment by unt0xication** [comment]
It works perfectly! Thank you 👍 Do you think you can add support for laravel dusk too?

**Comment by hitalos** [comment]
@unt0xication support to laravel dusk would increase the size of this image. You can extend this image for this.

**Comment by unt0xication** [comment]
@hitalos Ok thank you!

**Comment by MladenovicLazar** [comment]
Hey can you give me some advice how to connect xdebug on your docker image to phpstorm ? do i need some special configuration ? Thanks
