### ISSUE TITLE
Access to public folder

### ISSUE THREAD

**Issue by harishajdarevic** [hitalos/laravel#25]
I'm not able to access to /public folder. 

For example when I call http://localhost:4800/css/app.css 

I didn't get stylesheet. I'm still on homepage after above request. 

Any tip or advice? 

Thanks

**Comment by trueChazza** [comment]
Hi, your localhost environment is accessible?

**Comment by trueChazza** [comment]
Your localhost environment is accessible?

**Comment by harishajdarevic** [comment]
@trueChazza It's accessible as well.
Its problem in php built in server.
I switched to nginx and now everything works as expected :)
