### ISSUE TITLE
how to use `php artisan`?

### ISSUE THREAD

**Issue by sweida** [hitalos/laravel#27]
### after `docker-compose up -d`
how to use `php artisan` ?

### with  docker
```
docker run --name  -d -v $PWD:/var/www -p 80:80 hitalos/laravel
```
how to  use a database?

thank you very much!!!

**Comment by hitalos** [comment]
```
docker run --rm -v $PWD:/var/www hitalos/laravel php ./artisan ...
```

For database, follow the example on readme.
