### ISSUE TITLE
how to add php extension?

### ISSUE THREAD

**Issue by arthurdenti** [hitalos/laravel#29]
Hello, I am using the hitalos/laravel for a while now but just encountered an issue where I need to install the 'bc-math' extension to PHP I can access the bash inside the image but apt-install does not work. Any hint on how I can activate the extension in PHP? Thanks for any advice on this. Cheers. AD

**Comment by hitalos** [comment]
These images based on `php` and `php:alpine` coming with command `docker-php-ext-install`. You can use:
`docker-php-ext-install bc-math`

**Comment by arthurdenti** [comment]
Great! Thanks for the hint!
