### ISSUE TITLE
Could not open input file: ./artisan

### ISSUE THREAD

**Issue by phichu** [hitalos/laravel#3]
I pull this docker from docker hub.
and run docker run --name lara -d  -v lara:/var/www -p 8000:80 hitalos/laravel     

but it said Could not open input file: ./artisan 
I now its my mistake, please help what wrong with my command.

Thank you.

**Comment by hitalos** [comment]
Your volume needs to be a path to laravel.
Try mapping a new laravel instance:
```
composer create-project --prefer-dist laravel/laravel test
docker run --name lara -d -v $PWD/test:/var/www -p 8000:80 hitalos/laravel
```
