### ISSUE TITLE
Tags for using older versions of PHP?

### ISSUE THREAD

**Issue by Zhythero** [hitalos/laravel#31]
Hi thanks for maintaining this docker image.

This morning my pipeline builds are failing because my app only supports 7.2
Is there a way to use specific version like a docker tag? I can only see `latest` tag for now.
Thanks!

**Comment by hitalos** [comment]
I was going to suggest you fork. But I saw that you already did.
Your project doesn't run in PHP 7.4? Which is the error message?

**Comment by Zhythero** [comment]
My project has `pusher/pusher-php-server v3.4.1` library dependency which requires `php >=5.4 <7.4`, making my pipeline giving errors.

Anyways, I managed to solve my case by using `lorisleiva/laravel-docker:7.2` instead. Thanks for the response :)
