### ISSUE TITLE
Latest version does not include PGSQL driver

### ISSUE THREAD

**Issue by Alzy** [hitalos/laravel#33]
I spent the whole day the other day troubleshooting my bitbucket pipelines because all of a sudden it wasn't detecting the driver. Ended up fixing the issue by manually installing via the script:

          - set -ex && apk --no-cache add postgresql-libs postgresql-dev
          - docker-php-ext-install -j$(nproc) pgsql pdo_pgsql gd
          - apk del postgresql-dev

Now, one of my developers started having the same issue when running a fresh copy of our project. Resolved the issue using the same method. Out of curiosity, we tried setting the version explicitly to `hitalos/laravel:7` instead `hitalos/laravel:latest` and it worked out of the box. So it looks like `hitalos/laravel:latest` doesn't include the package at all anymore

**Comment by hitalos** [comment]
Sorry about that. PHP version 8 brought many changes. I'm fixing your problems right now.
I take this opportunity to reinforce the warning not to use this image in production, but as an example to build your own.

**Comment by Alzy** [comment]
> Sorry about that. PHP version 8 brought many changes. I'm fixing your problems right now.
> I take this opportunity to reinforce the warning not to use this image in production, but as an example to build your own.

Thank you. We're only using the image for development and testing. For production we're using a separate image.
