### ISSUE TITLE
Missing PDO Driver

### ISSUE THREAD

**Issue by mitni455** [hitalos/laravel#5]
PDOException in Connector.php line 55:
could not find driver

When using the example docker-compose file

**Comment by hitalos** [comment]
There was an error on compilation of mongodb php extension.
I had add `bash` to solve it.
Update image to latest version with:
`docker pull hitalos/laravel:latest`

**Comment by JorisKok** [comment]
I get the same error, even though I am using :latest

**Comment by sebsel** [comment]
I get the same error, when working with `mysql`. Using `sqlite` seems fine.

**Comment by hitalos** [comment]
I found some errors in php compilation because mcrypt was deprecated. Please, try with new image pushed now.
