### ISSUE TITLE
Unable to curl over HTTPS

### ISSUE THREAD

**Issue by richardcornelissen** [hitalos/laravel#6]
A curl over https resulted in a failure:
```
bash-4.3# curl https://google.com
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
```

Curl over HTTP did work:
```
bash-4.3# curl http://google.com
[some html that doesn't render well in github's issue tracker]
```

According to this link:
https://github.com/gliderlabs/docker-alpine/issues/148#issuecomment-193389471
It seems this rm -rf was the problem:
https://github.com/hitalos/laravel/blob/master/install-node.sh#L26

For now, we solved this with our own dockerfile:
```
FROM hitalos/laravel

#fix to also curl trusted https resources
RUN mkdir -p /etc/ssl/certs
RUN apk --no-cache add ca-certificates && update-ca-certificates
```

**Comment by hitalos** [comment]
Ok @richardcornelissen, I built this image for development and customization! 
In this current version, `ca-certificates` already installed. 
`mkdir -p /etc/ssl/certs && update-ca-certificates` should resolve.
Other way to avoid this error is using `-k` with curl.
