### ISSUE TITLE
could not find driver PDO_MYSQL module

### ISSUE THREAD

**Issue by JoanSerna** [hitalos/laravel#7]
`bash-4.3# php phpinfo.php | grep PDO`
`PDO`
`PDO support => enabled`
`PDO drivers => sqlite`
`PDO Driver for SQLite 3.x => enabled`
`bash-4.3# `

you need to enable pdo_mysql extension

**Comment by hitalos** [comment]
Hello @JoanSerna! There was an error in php extensions compilation in previous image. Try with the latest version (2 days ago).
