### ISSUE TITLE
Failed to open stream autoload.php

### ISSUE THREAD

**Issue by Cclleemm** [hitalos/laravel#8]
Hello,

I pulled your docker image on my server, I cloned my Laravel project in `/opt/aa/bb/laravel`
 
then I ran `docker run --name test -d -v /opt/aa/bb/laravel:/var/www -p 33080:80 hitalos/laravel`

but I obtained this container error when I looked at logs 
> Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/artisan on line 18

> Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/artisan on line 18

My container won't start

**Comment by hitalos** [comment]
Hello @Cclleemm!
This image does not build your project. You have to install dependencies, build assets…
If you starting from new project, try run this command before:
`docker run --rm -it -v /opt/aa/bb/laravel:/var/www hitalos/laravel composer install`

**Comment by Cclleemm** [comment]
@hitalos thank you. It works very well for me.
Very good Docker image !
